### ISSUE TITLE
Scatter Chart View V3.0 bad point displayed with BaloonMaker

### ISSUE THREAD

**Issue by thierryH91200** [danielgindi/Charts#1482]
macOS V3.0 Xcode 8.0

- to "Scatter Chart View" I created a BaloonMaker and when I click on a point on the graph is another point of the y axis is displayed
- some items have no values

it's all

thanks

                let  marker : BalloonMarker = BalloonMarker( color: #colorLiteral(red: 0.8039215803, green: 0.8039215803, blue: 0.8039215803, alpha: 1), font: NSFont.systemFont(ofSize: 12.0),  textColor: NSColor.white, insets: NSEdgeInsetsMake(8.0, 8.0, 20.0, 8.0))
                marker.minimumSize = CGSize( width: 80.0, height :40.0)
                scatterChartView.marker = marker

<img width="1669" alt="capture d ecran 2016-09-19 a 20 30 53" src="https://cloud.githubusercontent.com/assets/6251463/18644707/b5490edc-7eaa-11e6-9674-7f50c2417411.png">

**Comment by danielgindi** [comment]
It seems like the highlight is also in the incorrect position. But cannot reproduce this problem. Can you upload a sample project?

**Comment by thierryH91200** [comment]
Attached is an example of "scatter" based on os x Demo here is always the same point that is displayed with balloon marker
[ChartsDemo-OSX.zip](https://github.com/danielgindi/Charts/files/481641/ChartsDemo-OSX.zip)

thank you

**Comment by danielgindi** [comment]
@PhilJay There are two issues here, where the root of the problem is the fact that there are multiple values on same x-index.
1. The searching algorithm (Which I've fixed on both platforms)
2. The highlighter does not take this into account. We need to think about this for scatter and bubble charts where it makes sense to have multiple y-values for the same x-value

**Comment by PhilJay** [comment]
Yes, the fix was really required, I had just started fixing it myself when I saw your PR.
So I just committed my test case that I wrote for the fix and your PR passed :-)

The highlighters are an issue still. Do you want to tackle this before the release?

**Comment by danielgindi** [comment]
I'm not sure if this is a must - but it did work for bubbles before 3.0, so I guess we're supposed to :-)
