### ISSUE TITLE
Xcode 8 swift 3  No Such Module Charts?

### ISSUE THREAD

**Issue by roselind** [danielgindi/Charts#1494]
it is  'No Such Module Charts'   Error only when packing ,In the simulator or real machine running without error。（Xcode 8 swift 3 ）
![feb2e556-0a4e-4709-8372-d905ad9580f2](https://cloud.githubusercontent.com/assets/9067932/18662568/7aca44bc-7f4d-11e6-885a-ec720a12db63.png)
![b485d8b3-b6fa-45dc-9c24-a581079459db](https://cloud.githubusercontent.com/assets/9067932/18662617/b48bc446-7f4d-11e6-9239-8573aca9bb54.png)

**Comment by Huang-Libo** [comment]
@roselind 
Delete **Charts-ios** in _Target Dependencies_. That's too obvious...

**Comment by roselind** [comment]
It is still wrong  delete Charts-ios in Target Dependencies.

**Comment by roselind** [comment]
直接使用demo 里面生成的framework  ，希望 cocopod能 早日上传支持swift3版本的

**Comment by Huang-Libo** [comment]
Clean your project, then set up Embed Frameworks again.

**Comment by petester42** [comment]
The "Charts-iOS" target does not exist anymore. You need to set the Embed Framework to be "Charts". Makes sure you have the latest code from master. Clean and rebuild. That should work.

**Comment by roselind** [comment]
it is error  the use of the master branch 
![636c1c75-69fc-4cfc-be61-551819385b27](https://cloud.githubusercontent.com/assets/9067932/18705778/182f2de2-8022-11e6-885e-b26eed1b54ff.png)
![6cbe5bf6-4c95-4828-8668-6876e5d5f555](https://cloud.githubusercontent.com/assets/9067932/18705895/64c44ae8-8022-11e6-88d8-f0ea3b243725.png)

**Comment by liuxuan30** [comment]
I don't see this error with ChartsDemo on my side.

**Comment by kzuik** [comment]
Has this been resolved?

**Comment by roselind** [comment]
it is resolved  by Carthage

**Comment by vikash1307** [comment]
I am also facing same problem on my project. How to fix this ?

**Comment by yogeshR5** [comment]
+1

**Comment by nmneck** [comment]
Add 'Charts.framework' inside "Linked Frameworks and Libraries" and re-build your project.

**Comment by Andy1984** [comment]
The problem still exists when I am not using Cocoapods and Carthage. Is there any way to solve the problem?

**Comment by lorenzomilesi** [comment]
I was stuck on this problem with XCode 10.3, I think I've tried all the solutions I found on the internet for about 4 days.
It could be weird, but I fixed it by changing the project path: **I simply placed the project 2 or 3 folder outer** than before. It seems that the Swift compiler could not reach that nested folder level.
