### ISSUE TITLE
Legend Memory leak

### ISSUE THREAD

**Issue by basilmariano** [danielgindi/Charts#2130]
Hi,

I have a memory leak in my project, im using LineChartView. at first I though was my fault that i have set something that causes the memory leak, but when i tried the Charts Demo, I am surprised to encounter the same leak I had in my project.

Can someone suggest any fixes here?

Thanks in advance
![screen shot 2017-02-02 at 9 42 04 am](https://cloud.githubusercontent.com/assets/5466582/22534148/0869b71e-e92d-11e6-85ee-ef59def27939.png)
![screen shot 2017-02-02 at 9 42 16 am](https://cloud.githubusercontent.com/assets/5466582/22534151/0e338d3c-e92d-11e6-9ce6-8a3d614a8a84.png)

**Comment by petester42** [comment]
I believe you are right after inspecting it.

**Comment by basilmariano** [comment]
i've been inspecting this and I hope it's a Swift Bug.

**Comment by petester42** [comment]
I'll leave this open but I don't know why. On a device its worse :P. Maybe its because of the bridging to objc of the demo.

**Comment by basilmariano** [comment]
i also have a lot of leaks  in my project related to Charts. It might get rejected by apple .

**Comment by SvenMuc** [comment]
I performed the same test on my app. Seems that I found a memory leak the ChartDefaultValueFormatter.

![bildschirmfoto 2017-02-04 um 23 16 23](https://cloud.githubusercontent.com/assets/13385716/22621981/6770a89e-eb30-11e6-8e52-e433cd39db33.png)

**Comment by basilmariano** [comment]
did you try actual device? it's worse on a device. leaks everywhere. huhu

**Comment by petester42** [comment]
Memory leaks won't get your app rejected.

**Comment by basilmariano** [comment]
i added `deinit()` function in my viewControllers and `lineChartView` and it was called anyway so it should not give problem.

**Comment by ohtoritoritori** [comment]
How did you solve this?  I noticed the same thing in my app when using the line chart.

**Comment by liuxuan30** [comment]
we need to understand why it leaks, for what @SvenMuc pointed, one of my guess is the retain cycle, there is one post talking about it long time ago.

I roughly recall the formatter leak is because the delegate or the fomatter holder are the same one. I think it has been fixed to weak property now?

**Comment by dianamott** [comment]
I am still seeing this same leak in latest version of Charts running on Xcode 13.  It's causing my view controllers to not deinit which over time causes memory issues.  
I created my own extension on the AxisFormatDelegate and assigned it to  a weak var delegate yet it is still retaining.  
Anyone found a workaround to this problem?
