### ISSUE TITLE
Xcode 14 Issues (ASAP fix needed)

### ISSUE THREAD

**Issue by MichaelGrigoryan** [danielgindi/Charts#4903]
<img width="724" alt="Screen Shot 2022-09-13 at 11 30 47" src="https://user-images.githubusercontent.com/31137143/189838709-0f5752be-f99e-48d1-a377-270a3a93ad6d.png">

**Comment by sekny** [comment]
Any solution for this? I face the same with this issue.

**Comment by huseyinmetin** [comment]
I fixed it with the 4.1.0 update

`pod 'Charts', '~> 4.1.0'`
and
`pod install --repo-update`

**Comment by KeWangKW** [comment]
> 有什么解决办法吗？我面临同样的问题，无论如何我尝试更新到最新版本并得到另一个错误（当前目标：11.0） <img alt="图片" width="802" src="https://user-images.githubusercontent.com/10111179/189865172-98cbeec9-c21c-409f-b96c-4d6e344cfc0b.png">

Podfile:
platform :ios, '12.0'

**Comment by Lishuo15266176690** [comment]
Any solution for this? I face the same with this issue, anyway I trying to update to latest version and got another error(current target: 11.0)

[!] CocoaPods could not find compatible versions for pod "Charts":
  In Podfile:
    Charts (~> 4.1.0)

    ChartsRealm was resolved to 3.4.0, which depends on
      Charts (~> 3.4.0)

Specs satisfying the `Charts (~> 4.1.0), Charts (~> 3.4.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by EarthHeroOrg** [comment]
> Any solution for this? I face the same with this issue, anyway I trying to update to latest version and got another error(current target: 11.0) <img alt="image" width="802" src="https://user-images.githubusercontent.com/10111179/189865172-98cbeec9-c21c-409f-b96c-4d6e344cfc0b.png">

@sekny unfortunately it seems like ios 12 is the minimum supported version now.

**Comment by sethpoly** [comment]
Also seeing this issue, bumping version to 4.1.0 using SPM did not resolve the issue either.

**Comment by dhruvilpatel07** [comment]
@sethpoly for dependency rules select branch -> master using SPM. This fixed for me as of now.

**Comment by sekny** [comment]
> ChartsRealm

Cool @EarthHeroOrg,  Unfortunately my requirement is set the minimum target 11, is there any other better way?

**Comment by klawsachkar** [comment]
> @sethpoly for dependency rules select branch -> master using SPM. This fixed for me as of now.

are you sure, i tried that and it didnt work

**Comment by xgjyjy** [comment]
charts version: 3.6.0
Xcode verson: 14.0
The solution is: 
```
// MARK: RangeReplaceableCollection
extension ChartDataSet: RangeReplaceableCollection {
    
    // add this method
    public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
        entries.replaceSubrange(subrange, with: newElements)
        notifyDataSetChanged()
    }
    
    public func append(_ newElement: Element) {
        calcMinMax(entry: newElement)
        entries.append(newElement)
    }
```

**Comment by klawsachkar** [comment]
> Charts version: 3.6.0 Xcode version: 14.0 The solution is:
> 
> ```
> // MARK: RangeReplaceableCollection
> extension ChartDataSet: RangeReplaceableCollection {
>     
>     // add this method
>     public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
>         entries.replaceSubrange(subrange, with: newElements)
>         notifyDataSetChanged()
>     }
>     
>     public func append(_ newElement: Element) {
>         calcMinMax(entry: newElement)
>         entries.append(newElement)
>     }
> ```

have you used Pod or SPM for this?

and how did you add the missing conform to protocol method?

**Comment by idemche** [comment]
> <img alt="Screen Shot 2022-09-13 at 3 42 00 PM" width="1771" src="https://user-images.githubusercontent.com/3592933/189903751-984465a8-708e-4379-b1d1-c6fd2f12dfdc.png">
> 
> After i did pod 'Charts', '~> 4.1.0' and pod install --repo-update
> building the project would give these errors in Swift Algorithms that is a dependency from Charts.
> 
> Can someone help with the issue?

Try adding the following into `post_install do |installer|` in Podfile if you use Cocoapods:
`
if target.name == "SwiftAlgorithms"
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
 `

**Comment by KoichiroKAMADA** [comment]
Any solution for SPM?
I must use Charts version: 3.6.0.
I can not update latest one.
I need a solution for 3.6.0  via SPM.

**Comment by klawsachkar** [comment]
> > <img alt="Screen Shot 2022-09-13 at 3 42 00 PM" width="1771" src="https://user-images.githubusercontent.com/3592933/189903751-984465a8-708e-4379-b1d1-c6fd2f12dfdc.png">
> > After i did pod 'Charts', '~> 4.1.0' and pod install --repo-update
> > building the project would give these errors in Swift Algorithms that is a dependency from Charts.
> > Can someone help with the issue?
> 
> Try adding the following into `post_install do |installer|` in Podfile if you use Cocoapods so it looks like this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>         if target.name == "SwiftAlgorithms"
>            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
>        end
>     end
>   end
> end
> ```
> 
> and then run pod install. That might help

that solved it for me, thank you a lot

**Comment by sethpoly** [comment]
> @sethpoly for dependency rules select branch -> master using SPM. This fixed for me as of now.

Thank you! This solved the issue for now.

**Comment by Rylaa** [comment]
Can anyone explain how I can run charts new version?

I fixed it with the 4.1.0 update

pod 'Charts', '~> 4.1.0'
and
pod install --repo-update

When I try I got below error on m1 mac

[!] CocoaPods could not find compatible versions for pod "Charts":
  In Podfile:
    Charts (~> 4.1.0)

Specs satisfying the `Charts (~> 4.1.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by EarthHeroOrg** [comment]
> Can anyone explain how I can run charts new version?
> 
> pod 'Charts', '~> 4.1.0'
> 
> pod install --repo-update
> 
> When I try I got below error on m1 mac
> 
> [!] CocoaPods could not find compatible versions for pod "Charts": In Podfile: Charts (~> 4.1.0)
> 
> Specs satisfying the `Charts (~> 4.1.0)` dependency were found, but they required a higher minimum deployment target.

The minimum supported iOS version is 12 with Charts v4, so that might be your issue. See the conversation above for more details. If you are using iOS below 12 see the solution from [xgjyjy](https://github.com/xgjyjy)

**Comment by mayesdave** [comment]
> Try adding the following into `post_install do |installer|` in Podfile if you use Cocoapods so it looks like this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>         if target.name == "SwiftAlgorithms"
>            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
>        end
>     end
>   end
> end
> ```
> 
> and then run pod install. That might help

Thanks @idemche, That also worked for me...

**Comment by afridikhalid** [comment]
> > Can anyone explain how I can run charts new version?
> > pod 'Charts', '~> 4.1.0'
> > pod install --repo-update
> > When I try I got below error on m1 mac
> > [!] CocoaPods could not find compatible versions for pod "Charts": In Podfile: Charts (~> 4.1.0)
> > Specs satisfying the `Charts (~> 4.1.0)` dependency were found, but they required a higher minimum deployment target.
> 
> The minimum supported iOS version is 12 with Charts v4, so that might be your issue. See the conversation above for more details. If you are using iOS below 12 see the solution from [xgjyjy](https://github.com/xgjyjy)

I changed the Minimum supported iOS version to 12 but still it's not working

**Comment by jobscolin** [comment]
> Charts version: 3.6.0 Xcode version: 14.0 The solution is:
> 
> ```
> // MARK: RangeReplaceableCollection
> extension ChartDataSet: RangeReplaceableCollection {
>     
>     // add this method
>     public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
>         entries.replaceSubrange(subrange, with: newElements)
>         notifyDataSetChanged()
>     }
>     
>     public func append(_ newElement: Element) {
>         calcMinMax(entry: newElement)
>         entries.append(newElement)
>     }
> ```

可以！worked for me！

**Comment by huangzhengguo** [comment]
> > > Can anyone explain how I can run charts new version?
> > > pod 'Charts', '~> 4.1.0'
> > > pod install --repo-update
> > > When I try I got below error on m1 mac
> > > [!] CocoaPods could not find compatible versions for pod "Charts": In Podfile: Charts (~> 4.1.0)
> > > Specs satisfying the `Charts (~> 4.1.0)` dependency were found, but they required a higher minimum deployment target.
> > 
> > 
> > The minimum supported iOS version is 12 with Charts v4, so that might be your issue. See the conversation above for more details. If you are using iOS below 12 see the solution from [xgjyjy](https://github.com/xgjyjy)
> 
> I changed the Minimum supported iOS version to 12 but still it's not working

![20220916141025](https://user-images.githubusercontent.com/20478851/190569119-8aa60830-f24c-40d7-83c0-61ad1d07a739.jpg)
Have you change the ios Version in podfile?

**Comment by afridikhalid** [comment]
> > > > Can anyone explain how I can run charts new version?
> > > > pod 'Charts', '~> 4.1.0'
> > > > pod install --repo-update
> > > > When I try I got below error on m1 mac
> > > > [!] CocoaPods could not find compatible versions for pod "Charts": In Podfile: Charts (~> 4.1.0)
> > > > Specs satisfying the `Charts (~> 4.1.0)` dependency were found, but they required a higher minimum deployment target.
> > > 
> > > 
> > > The minimum supported iOS version is 12 with Charts v4, so that might be your issue. See the conversation above for more details. If you are using iOS below 12 see the solution from [xgjyjy](https://github.com/xgjyjy)
> > 
> > 
> > I changed the Minimum supported iOS version to 12 but still it's not working
> 
> ![20220916141025](https://user-images.githubusercontent.com/20478851/190569119-8aa60830-f24c-40d7-83c0-61ad1d07a739.jpg) Have you change the ios Version in podfile?

I had the same issue, if you're using Mac with M1 then before opening your terminal check the option Open using Rosetta and then open terminal and update your pods again.

![Screenshot 2022-09-16 at 9 59 24 AM](https://user-images.githubusercontent.com/3612353/190587743-20d13b91-9c0e-43e7-a0e6-f26eae9c01f1.png)
![Screenshot 2022-09-16 at 10 00 05 AM](https://user-images.githubusercontent.com/3612353/190587881-c5d36d48-659c-4dbc-a9b8-5304154f9f09.png)

**Comment by mortenkleveland** [comment]
> Any solution for SPM? I must use Charts version: 3.6.0. I can not update latest one. I need a solution for 3.6.0 via SPM.

You have to add the repo (zip of 3.6.0) locally like described here: https://developer.apple.com/documentation/xcode/editing-a-package-dependency-as-a-local-package
Then you can overwrite the function mentioned earlier in this thread.

**Comment by huhaopan** [comment]
> I fixed it with the 4.1.0 update
> 
> `pod 'Charts', '~> 4.1.0'` and `pod install --repo-update`

Thank you very much for helping me out

**Comment by pmairoldi** [comment]
Closing since the issue is resolved.
